### ISSUE TITLE
UI controls for server starting

### ISSUE THREAD

**Issue by jdh104** [mnmcknight/StupidGrayBlackjack#1]
We need to be able to instantiate the StupidServer class using the game's GUI.

* Add some button that says "Start a matchmaking server"
* Button should execute the following:
     `StupidServer s = Program.StartNewServer()`
* Button should change the frame to show a "close server" button that executes:
     `Program.CloseServer()`

Note
--------------------
The client doesn't need to play a game after starting server. The close server button can take them back to the main menu.

**Comment by BenToups** [comment]
it done
